spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/wechat_order?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  # 忽略json转换对象中的null值属性
  jackson:
    default-property-inclusion: non_null

#server:
#  context-path: /sell

# 微信授权 - 测试公众账号
#wechat:
#  mpAppId: wxbed905c16599f7ec
#  mpAppSecret: 3e8ac32d2c9ed134d929c23fa70393e6

# 微信支付
wechat:
  mpAppId: wxd898fcb01713c658
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: D:\develop\workspace\ws_idea_2017\wechat_order\h5.p12
  notifyUrl: http://fairy.nat300.top/notify