spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/wechat_order?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  # 忽略json转换对象中的null值属性
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell

wechat:
  myAppId: wxbed905c16599f7ec
  myAppSecret: 3e8ac32d2c9ed134d929c23fa70393e6